shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - undici-types
  - semver

packages:
  - .
  - playground/*
  - e2e/*
  - docs

allowBuilds:
  esbuild: true
  sharp: true
  simple-git-hooks: true
  unrs-resolver: true
  vue-demi: true

overrides:
  fumadocs-twoslash>twoslash: npm:twoslash-vue@^0.3.9

catalog:
  '@antfu/eslint-config': ^9.3.0
  '@eslint-react/eslint-plugin': ^5.18.0
  '@iconify-json/lucide': ^1.2.120
  '@iconify-json/simple-icons': ^1.2.92
  '@next/eslint-plugin-next': ^16.2.10
  '@nuxt/eslint': ^1.16.0
  '@nuxt/ui': ^4.10.0
  '@playwright/test': ^1.62.1
  '@react-router/dev': ^8
  '@react-router/node': ^8
  '@react-router/serve': ^8
  '@reactuses/core': ^6.5.2
  '@shikijs/transformers': ^4.4.3
  '@shikijs/twoslash': ^4.4.3
  '@standard-schema/spec': ^1.1.0
  '@tailwindcss/postcss': ^4.3.3
  '@tailwindcss/vite': ^4.2.2
  '@testing-library/react': ^16.3.2
  '@testing-library/vue': ^8.1.0
  '@types/mdast': ^4.0.4
  '@types/mdx': ^2.0.14
  '@types/node': ^26.1.2
  '@types/qs': ^6.15.0
  '@types/react': ^19.2.18
  '@types/react-dom': ^19
  '@vitejs/plugin-react': ^6.0.1
  '@vitejs/plugin-vue': ^6.0.5
  animejs: ^4.5.0
  arktype: ^2.2.3
  cnfast: ^0.1.0
  eslint: ^10.8.0
  eslint-plugin-react-refresh: ^0.5.3
  fumadocs-core: 16.14.3
  fumadocs-docgen: ^3.1.0
  fumadocs-mdx: 15.2.3
  fumadocs-twoslash: ^3.3.0
  fumadocs-typescript: ^5.3.0
  fumadocs-ui: npm:@fumadocs/base-ui@16.14.3
  happy-dom: ^20.11.2
  isbot: ^5.1.36
  jiti: ^2.7.0
  lint-staged: ^17.3.0
  lucide-react: ^1.28.0
  mdast-util-mdx-jsx: ^3.2.0
  # 16.3.0 is having an issue with useRouter() in pages router
  # (isolated to turbopack, perhaps a next.js regression)
  # should monitor later patches
  next: ~16.2.0
  nuxt: ^4.5.2
  postcss: ^8.5.25
  publint: ^0.3.23
  qs: ^6.15.0
  react: ^19.2.8
  react-dom: ^19.2.8
  react-router: ^8.3.0
  simple-git-hooks: ^2.13.1
  tailwindcss: ^4.3.3
  tsdown: ^0.22.14
  turbo: ^2.10.9
  twoslash: ^0.3.9
  twoslash-vue: ^0.3.9
  typescript: ^6.0.3
  unified: ^11.0.5
  unist-util-visit: ^5.1.0
  valibot: ^1.4.2
  vfile: ^6.0.3
  vite: ^8.0.3
  vitest: ^4.1.10
  vue: ^3.5.41
  vue-router: ^5.2.0
  vue-tsc: ^3.3.8
  zod: ^4.4.3
