shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - undici-types
  - semver

packages:
  - .
  - e2e/*
  - docs

allowBuilds:
  esbuild: true
  sharp: true
  simple-git-hooks: true
  unrs-resolver: true
  vue-demi: true

overrides:
  fumadocs-twoslash>twoslash: npm:twoslash-vue@^0.3.9

catalog:
  '@antfu/eslint-config': ^9.3.0
  '@changesets/changelog-github': ^1.0.0
  '@changesets/cli': ^3.0.1
  '@iconify-json/simple-icons': ^1.2.93
  '@playwright/test': ^1.62.1
  '@react-router/dev': ^8.3.0
  '@react-router/node': ^8.3.0
  '@react-router/serve': ^8.3.0
  '@reactuses/core': ^6.5.5
  '@shikijs/transformers': ^4.4.3
  '@shikijs/twoslash': ^4.4.3
  '@standard-schema/spec': ^1.1.0
  '@tailwindcss/postcss': ^4.3.3
  '@testing-library/react': ^16.3.2
  '@testing-library/vue': ^8.1.0
  '@types/mdast': ^4.0.4
  '@types/mdx': ^2.0.14
  '@types/node': ^26.2.0
  '@types/qs': ^6.15.1
  '@types/react': ^19.2.18
  '@types/react-dom': ^19.2.4
  '@vitejs/plugin-react': ^6.1.0
  '@vitejs/plugin-vue': ^6.0.8
  '@vue/server-renderer': ^3.5.41
  animejs: ^4.5.0
  arktype: ^2.2.3
  cnfast: ^0.1.0
  cross-env: ^10.1.0
  eslint: ^10.9.0
  fumadocs-core: 16.14.3
  fumadocs-docgen: ^3.1.0
  fumadocs-mdx: 15.2.3
  fumadocs-twoslash: ^3.3.0
  fumadocs-typescript: ^5.3.0
  fumadocs-ui: npm:@fumadocs/base-ui@16.14.3
  h3: 2.0.1-rc.29
  happy-dom: ^20.11.6
  isbot: ^5.2.1
  jiti: ^2.7.0
  lint-staged: ^17.3.0
  lucide-react: ^1.33.0
  mdast-util-find-and-replace: ^3.0.2
  mdast-util-mdx-jsx: ^3.2.0
  # 16.3.0 is having an issue with useRouter() in pages router
  # (isolated to turbopack, perhaps a next.js regression)
  # should monitor later patches
  next: ~16.2.12
  nuqs: ^2.10.0
  nuxt: ^4.5.2
  postcss: ^8.5.26
  publint: ^0.3.24
  qs: ^6.15.3
  react: ^19.2.8
  react-dom: ^19.2.8
  react-router: ^8.3.0
  simple-git-hooks: ^2.13.1
  tailwindcss: ^4.3.3
  tsdown: ^0.22.14
  turbo: ^2.10.11
  twoslash: ^0.3.9
  twoslash-vue: ^0.3.9
  typescript: ^6.0.3
  unified: ^11.0.5
  unist-util-visit: ^5.1.0
  valibot: ^1.4.2
  vfile: ^6.0.3
  vite: ^8.2.2
  vitest: ^4.1.11
  vue: ^3.5.41
  vue-router: ^5.2.0
  zod: ^4.4.3
