shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - undici-types
  - semver

packages:
  - playground/**

allowBuilds:
  esbuild: true
  sharp: true
  simple-git-hooks: true
  unrs-resolver: true
  vue-demi: true

catalog:
  '@antfu/eslint-config': ^9.1.0
  '@iconify-json/lucide': ^1.2.120
  '@iconify-json/simple-icons': ^1.2.92
  '@next/eslint-plugin-next': ^16.2.10
  '@nuxt/eslint': ^1.16.0
  '@nuxt/ui': ^4.10.0
  '@tailwindcss/postcss': ^4
  '@types/node': ^26.1.1
  '@types/react': ^19.2.17
  '@types/react-dom': ^19
  eslint: ^10.8.0
  jiti: ^2.7.0
  lint-staged: ^17.1.0
  next: ^16.2.10
  nuxt: ^4.5.1
  publint: ^0.3.21
  react: ^19.2.8
  react-dom: ^19.2.8
  simple-git-hooks: ^2.13.1
  tailwindcss: ^4.3.3
  tsdown: ^0.22.9
  typescript: ^6.0.3
  vitest: ^4.1.10
  vue: ^3.5.40
  vue-router: ^5.2.0
  vue-tsc: ^3.3.8
