export function isObject(data: unknown): data is Record<PropertyKey, unknown> {
  return typeof data === 'object' && data !== null && !Array.isArray(data)
}

export function isPlainObject(o: unknown): o is Record<PropertyKey, unknown> {
  if (!isObject(o))
    return false

  // modified constructor
  const ctor = o.constructor
  if (ctor === undefined)
    return true

  if (typeof ctor !== 'function')
    return true

  // modified prototype
  const prot = ctor.prototype
  if (!isObject(prot))
    return false

  // ctor doesn't have static `isPrototypeOf`
  return Object.hasOwn(prot, 'isPrototypeOf')
}

export function shallowClone<T>(o: T): T {
  if (isPlainObject(o))
    return { ...o }
  if (Array.isArray(o))
    return [...o] as T
  if (o instanceof Map)
    return new Map(o) as T
  if (o instanceof Set)
    return new Set(o) as T
  return o
}

/**
 * Creates a new object composed of the picked object properties.
 *
 * This function takes an object and an array of keys, and returns a new object that
 * includes only the properties corresponding to the specified keys.
 *
 * @template T - The type of object.
 * @template K - The type of keys in object.
 * @param obj - The object to pick keys from.
 * @param keys - An array of keys to be picked from the object.
 * @returns A new object with the specified keys picked.
 *
 * @example
 * const obj = { a: 1, b: 2, c: 3 };
 * const result = pick(obj, ['a', 'c']);
 * // result will be { a: 1, c: 3 }
 */
export function pick<T extends Record<string, any>, K extends keyof T>(obj: T, keys: readonly K[]): Pick<T, K> {
  const result = {} as Pick<T, K>

  for (let i = 0; i < keys.length; i++) {
    const key = keys[i]!

    if (Object.hasOwn(obj, key)) {
      result[key] = obj[key]
    }
  }

  return result
}

/**
 * Creates a new object with the same keys as the given object, but with values generated
 * by running each own enumerable property of the object through the iteratee function.
 *
 * @template T - The type of the object.
 * @template K - The type of the keys in the object.
 * @template V - The type of the new values generated by the iteratee function.
 *
 * @param object - The object to iterate over.
 * @param getNewValue - The function invoked per own enumerable property.
 * @returns Returns the new mapped object.
 *
 * @example
 * // Example usage:
 * const obj = { a: 1, b: 2 };
 * const result = mapValues(obj, (value) => value * 2);
 * console.log(result); // { a: 2, b: 4 }
 */
export function mapValues<T extends object, K extends keyof T, V>(
  object: T,
  getNewValue: (value: T[K], key: K, object: T) => V,
): Record<K, V> {
  const result = {} as Record<K, V>
  const keys = Object.keys(object)

  for (let i = 0; i < keys.length; i++) {
    const key = keys[i] as K
    const value = object[key]

    result[key] = getNewValue(value, key, object)
  }

  return result
}
